# Generated by Django 4.2.6 on 2023-10-06 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=225)),
                ('description', models.CharField(max_length=225)),
                ('period', models.CharField(max_length=225)),
                ('technologiesSkills', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='technologySkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
