# Generated by Django 4.2.6 on 2023-10-06 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='technologiesSkills',
        ),
        migrations.AddField(
            model_name='experience',
            name='technologiesSkills',
            field=models.ManyToManyField(to='experiences.technologyskill'),
        ),
    ]
